export enum OfferTypes{
    FETCH_OFFER_REQUEST = "FETCH_OFFER_REQUEST",
    FETCH_OFFER_SUCCESS = "FETCH_OFFER_SUCCESS",
    FETCH_OFFER_FAILURE = "FETCH_OFFER_FAILURE",
    CREATE_OFFER_REQUEST = "CREATE_OFFER_REQUEST",
    CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS",
    CREATE_OFFER_FAILURE = "CREATE_OFFER_FAILURE",
    UPDATE_OFFER_REQUEST = "UPDATE_OFFER_REQUEST",
    UPDATE_OFFER_SUCCESS = "UPDATE_OFFER_SUCCESS",
    UPDATE_OFFER_FAILURE = "UPDATE_OFFER_FAILURE",
    TAKE_OFFER_REQUEST = "TAKE_OFFER_REQUEST",
    TAKE_OFFER_SUCCESS = "TAKE_OFFER_SUCCESS",
    TAKE_OFFER_FAILURE = "TAKE_OFFER_FAILURE",
}