export enum  ProfessionalTypes{
    FETCH_PROFESSIONAL_REQUEST = "FETCH_PROFESSIONAL_REQUEST",
    FETCH_PROFESSIONAL_SUCCESS = "FETCH_PROFESSIONAL_SUCCESS",
    FETCH_PROFESSIONAL_FAILURE = "FETCH_PROFESSIONAL_FAILURE",

    GET_SINGLE_PROFESSIONAL_REQUEST = "GET_SINGLE_PROFESSIONAL_REQUEST",
    GET_SINGLE_PROFESSIONAL_SUCCESS = "GET_SINGLE_PROFESSIONAL_SUCCESS",
    GET_SINGLE_PROFESSIONAL_FAILURE = "GET_SINGLE_PROFESSIONAL_FAILURE",

    UPDATE_SINGLE_USER_REQUEST = "UPDATE_SINGLE_USER_REQUEST",
    UPDATE_SINGLE_USER_SUCCESS = "UPDATE_SINGLE_USER_SUCCESS",
    UPDATE_SINGLE_USER_FAILURE = "UPDATE_SINGLE_USER_FAILURE",

}