export enum  ProfessionalTypes{
    FETCH_PROFESSIONAL_REQUEST = "FETCH_PROFESSIONAL_REQUEST",
    FETCH_PROFESSIONAL_SUCCESS = "FETCH_PROFESSIONAL_SUCCESS",
    FETCH_PROFESSIONAL_FAILURE = "FETCH_PROFESSIONAL_FAILURE",

}